title: 小周工作日记
description: 再努力一些！
baseurl: ""  
theme: null  

collections:
  categories:
    output: true
    permalink: /:path/
defaults:
  - scope:
      path: ""
      type: categories
    values:
      layout: category
plugins:
  - jekyll-toc
  
navigation:
  - title: 首页
    url: /
  - title: 关于
    url: /about
  - title: Java基础
    url: /java
  - title: Java并发
    url: /java_juc  
  - title: Database
    url: /database
