# 基础配置
title: 小周工作日记
description: 再努力一些！
baseurl: ""
theme: null 
timezone: Asia/Shanghai

# 集合配置
collections:
  java_basic:
    output: true
    permalink: /java/:slug/
  java_jvm:
    output: true
    permalink: /jvm/:slug/
  java_juc:
    output: true
    permalink: /juc/:slug/
  java_ssm:
    output: true
    permalink: /ssm/:slug/
  database_mysql:
    output: true
    permalink: /mysql/:slug/
  database_redis:
    output: true
    permalink: /redis/:slug/
  project:
    output: true
    permalink: /project/:slug/

# 默认布局
defaults:
  - scope:
      path: "" # 全局默认
    values:
      layout: "post"
      render_with_liquid: false
      show_toc: true
  - scope:
      path: "_java_basic"  
      type: "java_basic"
    values:
      slug: "java-basis"
      category: "java"
  - scope:
      path: "_java_juc"    
      type: "java_juc"
    values:
      slug: "java-juc"
      category: "juc"
  - scope:
      path: "_java_jvm"   
      type: "java_jvm"
    values:
      slug: "java-jvm"
      category: "jvm"
  - scope:
      path: "_java_ssm"   
      type: "java_ssm"
    values:
      slug: "java-ssm"
      category: "ssm"
  - scope:
      path: "_database_mysql"   
      type: "database_mysql"
    values:
      slug: "database-mysql"
      category: "mysql"
  - scope:
      path: "_database_redis"   
      type: "database_redis"
    values:
      slug: "database-redis"
      category: "redis"
  - scope:
      path: "_project"   
      type: "project"
    values:
      slug: "project"
      category: "project"

# 插件
plugins:
  - jekyll-toc
  - jekyll-paginate
  - jekyll-seo-tag

# 导航菜单
navigation:
  - title: 首页
    url: /
  - title: JAVA
    url: /java/
  - title: JVM
    url: /jvm/ 
  - title: JUC
    url: /juc/ 
  - title: SSM
    url: /ssm/   
  - title: MySQL
    url: /mysql/
  - title: Redis
    url: /redis/
  - title: PROJECT
    url: /project/
